vich_uploader:
  db_driver: orm

  mappings:
    offre_image:
      uri_prefix: /upload
      upload_destination: '%kernel.project_dir%/public/upload'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
